# Generated by Django 4.2.5 on 2024-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
