# Generated by Django 4.2.5 on 2024-03-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0002_rename_name_item_title_item_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
