# Generated by Django 4.2.5 on 2024-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0005_item_delegation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='delegation_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Independent', 'Independent')], max_length=100),
        ),
    ]
