# Generated by Django 4.2.5 on 2024-03-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0008_cart_cartitem_cart_items_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
