# Generated by Django 4.2.5 on 2024-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0010_item_created_at_item_is_sold_item_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
    ]
