# Generated by Django 4.2.5 on 2024-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0013_alter_item_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(),
        ),
    ]
