# Generated by Django 4.2.5 on 2024-04-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0014_alter_item_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_visible',
        ),
    ]
