# Generated by Django 4.2.5 on 2024-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0015_remove_item_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
