# Generated by Django 4.2.5 on 2024-04-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0016_item_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_visible',
            new_name='visible_to_customers',
        ),
    ]
