# Generated by Django 4.2.5 on 2024-04-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0019_alter_item_visible_to_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='visible_to_customers',
            new_name='is_visible',
        ),
    ]
