# Generated by Django 4.2.5 on 2024-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0020_rename_visible_to_customers_item_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
