# Generated by Django 4.2.5 on 2024-05-07 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, numbers, underscores, periods, and spaces only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain letters, numbers, underscores, periods, and spaces.', regex='^[\\w .]*$')]),
        ),
    ]
