# Generated by Django 4.2.5 on 2024-04-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
